### ISSUE TITLE
Flutter build is broken.

### ISSUE THREAD

**Issue by Dana-Ferguson** [pinkfish/flutter_native_timezone#1]
Please see issue Dana-Ferguson/time_machine#5. (Reprinted below)

```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
Because flutter_native_timezone 1.0.0 requires SDK version >=1.9.0 <2.0.0 and no versions of 
flutter_native_timezone match >1.0.0 <2.0.0, flutter_native_timezone ^1.0.0 is forbidden.
So, because flutter_calender depends on flutter_native_timezone ^1.0.0, version solving failed.
```

Background information: I created date and time API for use in Dart and on Flutter your library can be used to directly get the user's timezone (vs. a heuristic solver which normally works, but can never be guaranteed).

Is it possible to get [pubspec yaml updated](https://www.dartlang.org/dart-2#upper-constraints-on-the-sdk-version) for Dart 2.0? 

Thank you, :)

**Comment by pinkfish** [comment]
Fixing this now.

**Comment by pinkfish** [comment]
Fixed.
