### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dmrcierhn** [pinkfish/flutter_native_timezone#20]
![Ekran Alıntısı](https://user-images.githubusercontent.com/63152925/109875143-1c28e680-7c81-11eb-8c11-6689da2a2d21.PNG)

I get an error like this when trying to compile my project. How can I fix ? thank you

**Comment by pinkfish** [comment]
This is compiling for me?  A fix was just checked in for the ios build.

**Comment by kuhnroyal** [comment]
The fix in `1.0.9` doesn't work for me.

**Comment by dmrcierhn** [comment]
This error then disappeared, now it works for me

**Comment by pinkfish** [comment]
Weird, I compiled it for ios on my machine on a mac mini and it was working
for me yesterday.  the 1.0.9 version still doesn't work for you?  Might
need to try and clean the pod directory and do a pod install again?

**Comment by kuhnroyal** [comment]
It is compiling for iOS but the pod is removed. Just cleared everything, fresh project checkout. Not working.

**Comment by pinkfish** [comment]
Ok, just pushes a version 1.0.10 that fixes this for me.

**Comment by kuhnroyal** [comment]
Thanks, can confirm that this one works on iOS.
