### ISSUE TITLE
Indian Timezone showing "Asia/Calcutta" instead of "Asia/Kolkata"

### ISSUE THREAD

**Issue by NagaprabhuNagarajan** [pinkfish/flutter_native_timezone#52]
Our Indian Timezone, especially "Asia/Calcutta" was the name changed to "Asia/Kolkata" a very long ago. But still, our package provides the previous timezone name. It is the right time to update our timezone database.

**Comment by tjarvstrand** [comment]
Hi @NagaprabhuNagarajan 

This package has not been update for more than 18 months and author is not responding to issues. Consider switching to [flutter_timezone](https://pub.dev/packages/flutter_timezone) which is a fork of this repo.

That said, neither package contains its own timezone database. They only forward whatever value is reported by the current device's platform.

**Comment by NagaprabhuNagarajan** [comment]
> Hi @NagaprabhuNagarajan
> 
> This package has not been updated for more than 18 months and the author is not responding to issues or pull requests. Consider switching to [flutter_timezone](https://pub.dev/packages/flutter_timezone) which is a fork of this repo.
> 
> That said, neither package contains its own timezone database. They only forward whatever value is reported by the current device's platform.

Hi @tjarvstrand 
Thanks for your reply
