### ISSUE TITLE
Timezone Mexico_City

### ISSUE THREAD

**Issue by lcarielo** [pinkfish/flutter_native_timezone#54]
Daylight saving time no longer exists in Mexico City. please correct it. Greetings.

**Comment by tjarvstrand** [comment]
Hi @lcarielo 

This repository is no longer maintained and the author hasn't replied to issues in a long while. Consider switching to https://pub.dev/packages/flutter_timezone which is a fork.

That said, neither package contains its own timezone database, they only pass on what the native platform reports.

**Comment by lcarielo** [comment]
Thank you very much
