### ISSUE TITLE
Add ability to query supported timezones

### ISSUE THREAD

**Issue by MaikuB** [pinkfish/flutter_native_timezone#8]
Hey was looking to originally create a similar plugin but noticed you had created one already. This is to help solve the problem I've currently got in the local notifications plugin when scheduling notifications. I'm looking to see if a method could be added to query the list of supported timezones. Should be possible and was going to look at trying to submit a PR. However, when I use Android Studio to open the example Android app, it's not able to resolve the paths such that it can also show the plugin code in the IDE. Perhaps the plugin needs to be recreated to resolve the issue. Is this something you're able to look into?

**Comment by pinkfish** [comment]
This has been added too.  Thanks!
